apiVersion: v1
kind: Service
metadata:
  name: prod-mongodb-service
  namespace: iterview-prod
spec:
  type: ClusterIP
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    db: prod-iterview-mongodb