apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  namespace: iterview-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      db: prod-iterview-mongodb
  template:
    metadata:
      labels:
        db: prod-iterview-mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:latest
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongodb-data
              mountPath: /data/db
          livenessProbe:
            tcpSocket:
              port: 27017
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 27017
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 256Mi
      volumes:
        - name: mongodb-data
          emptyDir: {}