apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  labels:
    app: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:v2.27.1
          args:
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/prometheus"
          ports:
            - name: web
              containerPort: 9090
          volumeMounts:
            - name: prometheus-server-conf
              mountPath: /etc/prometheus/
            - name: prometheus-pv
              mountPath: /prometheus/
      volumes:
        - name: prometheus-server-conf
          configMap:
            name: prometheus-server-conf
        - name: prometheus-pv
          persistentVolumeClaim:
            claimName: prometheus-pvc
