apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-mongodb-deployment
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      db: {{ .Release.Name }}-mongodb
  template:
    metadata:
      labels:
        db: {{ .Release.Name }}-mongodb
    spec:
      containers:
          - name: mongodb
            image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            ports:
              - containerPort: 27017
            volumeMounts:
              - name: mongodb-data
                mountPath: /data/db
            resources:
              limits:
                cpu: "500m"
                memory: "512Mi"
              requests:
                cpu: "100m"
                memory: "256Mi"
      volumes:
        - name: mongodb-data
          emptyDir: {}
      restartPolicy: Always
